version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    volumes:
      - /home/suso/DockerWorking/ES/data/kibana.yml
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://localhost:9200
